function export_SST_posns(filename, SST_posns)
% export_SST_posns(filename, data)
% Write the positions computed based on SST to filename.

global options;

fid = 0;
[fid, message] = fopen(filename, 'w');
if fid == -1
    disp([filename, ': ', message])
    return;
end

fprintf('Stage 5 of 5: writing output to %s.\n', filename);

fprintf(fid, 'OID, search_box_width, search_box_height, position_lat_limit, north_limit, south_limit, max_pixels_exam, cloud_ignored, delta_t, date, month, numtemps, mintemp, maxtemp, medtemp, HDF_start_year, HDF_start_day, HDF_end_year, HDF_end_day, lat_SST, lat_light, lat, long, index1_max, max_poss_index1, index1_num_tied, index1_latmin, index1_latmax, index1_latmed, index2_max, max_poss_index2, index2_num_tied, index2_latmin, index2_latmax, index2_latmed, min_index3, index3_num_tied, index3_latmin, index3_latmax, index3_latmed, lat_step, long_step, slope, intercept\r\n');

num_posns = size(SST_posns, 2);
for i = 1:num_posns
	v =	datevec(SST_posns(i).date);
	fprintf(fid, '%d,%d,%d,%.2f,%.2f,%.2f,%d,%d,%.2f,%s,%d,%d,%.2f,%.2f,%.2f,%d,%d,%d,%d,%.3f,%.3f,%.3f,%.6f,%.6f,%.3f,%.3f,%.3f,%.3f,%.6f,%.6f,%.3f,%.3f,%.3f,%.3f,%e,%d,%.2f,%.2f,%.2f,%e,%f,%f,%d\r\n', ...
		i, options.search_width, options.search_height, options.delta_lat, ...
			SST_posns(i).north_limit, SST_posns(i).south_limit, SST_posns(i).max_pixels, SST_posns(i).cloud_ignored, options.delta_t, ...
			datestr(SST_posns(i).date), v(2), SST_posns(i).numtemps, SST_posns(i).mintemp, SST_posns(i).maxtemp, ...
			SST_posns(i).medtemp, SST_posns(i).start_year, SST_posns(i).start_day, ...
			SST_posns(i).end_year, SST_posns(i).end_day, SST_posns(i).SST_lat, SST_posns(i).light_lat, ...
			SST_posns(i).SST_lat, SST_posns(i).long, ...
		SST_posns(i).max_val_1, SST_posns(i).max_poss_index1, SST_posns(i).num_max_values_1, SST_posns(i).latmin_1, ...
			SST_posns(i).latmax_1, SST_posns(i).latmed_1, ...
		SST_posns(i).max_val_2, SST_posns(i).max_poss_index2, SST_posns(i).num_max_values_2, SST_posns(i).latmin_2, ...
			SST_posns(i).latmax_2, SST_posns(i).latmed_2, ...
		SST_posns(i).min_val_3, SST_posns(i).num_min_values_3, ...
				SST_posns(i).latmin_3, SST_posns(i).latmax_3, SST_posns(i).latmed_3, ...
		SST_posns(i).lat_step, SST_posns(i).long_step, SST_posns(i).slope, SST_posns(i).intercept);
end
fclose(fid);
end
